CREATE SEQUENCE SEQ_PONTO_COLETA
START WITH 1
INCREMENT BY 1;

CREATE TABLE TB_PONTO_COLETA (

    ID NUMBER PRIMARY KEY,

    NOME VARCHAR2(100) NOT NULL,

    ENDERECO VARCHAR2(255) NOT NULL,

    TIPO_RESIDUO VARCHAR2(80) NOT NULL,

    CAPACIDADE NUMBER(10) NOT NULL,

    ATIVO NUMBER(1) DEFAULT 1 NOT NULL,

    CONSTRAINT CK_TB_PONTO_COLETA_ATIVO
    CHECK (ATIVO IN (0,1))
);