INSERT INTO TB_PONTO_COLETA
(ID, NOME, ENDERECO, TIPO_RESIDUO, CAPACIDADE, ATIVO)
VALUES
(SEQ_PONTO_COLETA.NEXTVAL,
'Eco Ponto Centro',
'Rua Principal, 100',
'Plastico',
150,
1);

INSERT INTO TB_PONTO_COLETA
(ID, NOME, ENDERECO, TIPO_RESIDUO, CAPACIDADE, ATIVO)
VALUES
(SEQ_PONTO_COLETA.NEXTVAL,
'Coleta Sustentavel Norte',
'Av. Sustentabilidade, 250',
'Vidro',
200,
1);

INSERT INTO TB_PONTO_COLETA
(ID, NOME, ENDERECO, TIPO_RESIDUO, CAPACIDADE, ATIVO)
VALUES
(SEQ_PONTO_COLETA.NEXTVAL,
'Ponto Verde Sul',
'Rua das Flores, 88',
'Papel',
120,
1);